-- PostgreSQL Database Schema for Spacece CRM

-- 1. Contacts Table
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    linked_student_class TEXT,
    tags TEXT[] DEFAULT '{}',
    status TEXT DEFAULT 'Active',
    opted_out BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Inquiries Table
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES public.contacts(id) ON DELETE CASCADE,
    pipeline_stage TEXT DEFAULT 'New Inquiry',
    follow_up_date TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES public.contacts(id) ON DELETE CASCADE,
    direction TEXT NOT NULL,
    type TEXT NOT NULL,
    content TEXT,
    status TEXT DEFAULT 'sent',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Templates Table
CREATE TABLE IF NOT EXISTS public.templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    status TEXT DEFAULT 'APPROVED',
    message_body TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Campaigns Table
CREATE TABLE IF NOT EXISTS public.campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    template_id BIGINT REFERENCES public.templates(id) ON DELETE SET NULL,
    audience_type TEXT,
    status TEXT DEFAULT 'DRAFT',
    sent_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Media Metadata Table
CREATE TABLE IF NOT EXISTS public.media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_url TEXT NOT NULL,
    size TEXT,
    upload_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. WhatsApp Settings Table
CREATE TABLE IF NOT EXISTS public.whatsapp_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT,
    phone_number TEXT,
    phone_number_id TEXT,
    waba_id TEXT,
    access_token TEXT,
    connection_status TEXT DEFAULT 'DISCONNECTED',
    last_checked TIMESTAMPTZ,
    webhook_url TEXT,
    webhook_secret TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Subscriptions Table
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name TEXT NOT NULL,
    contact_limit INT DEFAULT 1000,
    message_limit INT DEFAULT 10000,
    contacts_used INT DEFAULT 0,
    messages_used INT DEFAULT 0,
    status TEXT DEFAULT 'Active',
    renewal_date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Payment History Table
CREATE TABLE IF NOT EXISTS public.payment_history (
    id TEXT PRIMARY KEY,
    subscription_id BIGINT REFERENCES public.subscriptions(id) ON DELETE CASCADE,
    date TEXT,
    amount TEXT,
    plan TEXT,
    status TEXT,
    invoice_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Automation Rules Table
CREATE TABLE IF NOT EXISTS public.automation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    trigger_event TEXT NOT NULL,
    conditions JSONB DEFAULT '[]'::jsonb,
    actions JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'ACTIVE',
    execution_count INT DEFAULT 0,
    last_executed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Automation Logs Table
CREATE TABLE IF NOT EXISTS public.automation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT REFERENCES public.automation_rules(id) ON DELETE SET NULL,
    rule_name TEXT,
    type TEXT,
    recipient TEXT,
    contact_id BIGINT REFERENCES public.contacts(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'SUCCESS',
    notes TEXT,
    conditions_evaluated TEXT,
    actions_executed TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for optimal performance
CREATE INDEX IF NOT EXISTS idx_contacts_phone ON public.contacts(phone);
CREATE INDEX IF NOT EXISTS idx_contacts_name ON public.contacts(name);
CREATE INDEX IF NOT EXISTS idx_inquiries_contact_id ON public.inquiries(contact_id);
CREATE INDEX IF NOT EXISTS idx_inquiries_pipeline_stage ON public.inquiries(pipeline_stage);
CREATE INDEX IF NOT EXISTS idx_messages_contact_id ON public.messages(contact_id);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON public.messages(timestamp);
CREATE INDEX IF NOT EXISTS idx_campaigns_template_id ON public.campaigns(template_id);
CREATE INDEX IF NOT EXISTS idx_automation_logs_rule_id ON public.automation_logs(rule_id);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_logs ENABLE ROW LEVEL SECURITY;

-- Permissive policies for standard application operation
CREATE POLICY "Allow public read access on contacts" ON public.contacts FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update/delete on contacts" ON public.contacts FOR ALL USING (true);

CREATE POLICY "Allow public access on inquiries" ON public.inquiries FOR ALL USING (true);
CREATE POLICY "Allow public access on messages" ON public.messages FOR ALL USING (true);
CREATE POLICY "Allow public access on templates" ON public.templates FOR ALL USING (true);
CREATE POLICY "Allow public access on campaigns" ON public.campaigns FOR ALL USING (true);
CREATE POLICY "Allow public access on media" ON public.media FOR ALL USING (true);
CREATE POLICY "Allow public access on whatsapp_settings" ON public.whatsapp_settings FOR ALL USING (true);
CREATE POLICY "Allow public access on subscriptions" ON public.subscriptions FOR ALL USING (true);
CREATE POLICY "Allow public access on payment_history" ON public.payment_history FOR ALL USING (true);
CREATE POLICY "Allow public access on automation_rules" ON public.automation_rules FOR ALL USING (true);
CREATE POLICY "Allow public access on automation_logs" ON public.automation_logs FOR ALL USING (true);
